import "./shell.css";
import "../styles/tokens.css";
import "../styles/typography.css";
import "../styles/themes.css";
import "../styles/layout.css";
import "../styles/buttons.css";
import "../styles/forms.css";
import "../styles/cards.css";
import "../modules/auth/auth.page.css";
import "../modules/decks/decks.page.css";
import "../modules/cards/cards.page.css";
import "../modules/study/study.page.css";
import "../modules/explore/explore.page.css";
import "../modules/stats/stats.page.css";
import "../modules/settings/settings.page.css";
import { createRouter } from "./router";
import { registerServiceWorker } from "../shared/pwa/register-sw";

createRouter(document.querySelector("#app") as HTMLElement);
registerServiceWorker();
